Repository trendmicro/cloudone-filestorage-plugins, pull requests merged in 2021-03, with the labels that each got.

#30 feat: Adding integration with microsoft teams and fss
  post-scan-actions/aws-python-teams-notification/README.md
  post-scan-actions/aws-python-teams-notification/handler.py
Labels: new plugin

#35 docs: Add options of parameters in description for SAR
  post-scan-actions/aws-python-promote-or-quarantine/template.yml
Labels: documentation

#37 chore: Add issue and PR templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_plugin_request.md
  .github/pull_request_template.md
Labels: documentation

#41 fix: FSS integration with ms-teams
  post-scan-actions/aws-python-teams-notification/handler.py
Labels: bug

#38 feat: fss-to-conformity-custom-check
  .gitignore
  post-scan-actions/aws-python-conformity-custom-check/README.md
  post-scan-actions/aws-python-conformity-custom-check/handler.py
  post-scan-actions/aws-python-conformity-custom-check/template.yml
Labels: new plugin
