Repository trendmicro/cloudone-filestorage-plugins, pull requests merged in 2021-06, with the labels that each got.

#53 feat: Add Terraform template for FSS aws stacks deployment
  .gitignore
  deployment/aws-terraform/README.md
  deployment/aws-terraform/all-in-one/main.tf
  deployment/aws-terraform/scanner-stack/main.tf
  deployment/aws-terraform/storage-stack/main.tf
Labels: new plugin

#49 feat: automate storage stack
  deployment/aws-python-storage-stack-automation/README.md
  deployment/aws-python-storage-stack-automation/architecture.png
  deployment/aws-python-storage-stack-automation/storage_stack.yaml
Labels: new plugin

#54 feat: FSS storage lifecycle
  deployment/aws-python-storage-stack-automation/README.md
  deployment/aws-python-storage-stack-automation/architecture.png
  deployment/aws-python-storage-stack-automation/storage_stack_lifecycle.yaml
Labels: enhancement

#58 fixed syntax error on line number 147 and 148
  post-scan-actions/aws-python-promote-or-quarantine/handler.py
Labels: bug
