Repository trendmicro/cloudone-filestorage-plugins, pull requests merged in 2021-12, with the labels that each got.

#73 feat: Add Azure slack notification plugin
  post-scan-actions/azure-python-slack-notification/.gitignore
  post-scan-actions/azure-python-slack-notification/README.md
  post-scan-actions/azure-python-slack-notification/slackNotification/.funcignore
  post-scan-actions/azure-python-slack-notification/slackNotification/ScanResultHandler/__init__.py
  post-scan-actions/azure-python-slack-notification/slackNotification/ScanResultHandler/function.json
  post-scan-actions/azure-python-slack-notification/slackNotification/ScanResultHandler/handler.py
  post-scan-actions/azure-python-slack-notification/slackNotification/host.json
  post-scan-actions/azure-python-slack-notification/slackNotification/requirements.txt
  post-scan-actions/azure-python-slack-notification/template.json
Labels: new plugin

#76 fix: Update bestzip
  post-scan-actions/aws-nodejs-securityhub-integration/lambda/package-lock.json
  post-scan-actions/aws-nodejs-securityhub-integration/lambda/package.json
Labels: bug

#75 fix: Remove bucket name constraint to allow dot(.)
  post-scan-actions/aws-python-promote-or-quarantine/template.yml
Labels: bug, enhancement
