Repository trendmicro/cloudone-filestorage-plugins, pull requests merged in 2021-02, with the labels that each got.

#26 feat: Adding Slack Notification integration with FSS
  post-scan-actions/aws-python-slack-notification/Makefile
  post-scan-actions/aws-python-slack-notification/README.md
  post-scan-actions/aws-python-slack-notification/handler.py
Labels: new plugin

#27 docs: add missing command and flags to CLI instructions
  post-scan-actions/aws-python-promote-or-quarantine/README.md
Labels: bug, documentation

#29 feat: add optional lambda environment variables
  post-scan-actions/aws-python-promote-or-quarantine/README.md
  post-scan-actions/aws-python-promote-or-quarantine/handler.py
Labels: enhancement

#32 fix: Add parameter default value to fix SAR required parameter
  post-scan-actions/aws-python-promote-or-quarantine/template.yml
Labels: bug
