Repository trendmicro/cloudone-filestorage-plugins, pull requests merged in 2022-09, with the labels that each got.

#92 feat(deployment): Add quality updates to terraform deployment
  deployment/aws-terraform/all-in-one/main.tf
  deployment/aws-terraform/all-in-one/outputs.tf
  deployment/aws-terraform/all-in-one/providers.tf
  deployment/aws-terraform/all-in-one/variables.tf
  deployment/aws-terraform/scanner-stack/main.tf
  deployment/aws-terraform/scanner-stack/outputs.tf
  deployment/aws-terraform/scanner-stack/providers.tf
  deployment/aws-terraform/scanner-stack/variables.tf
  deployment/aws-terraform/storage-stack/main.tf
  deployment/aws-terraform/storage-stack/outputs.tf
  deployment/aws-terraform/storage-stack/providers.tf
  deployment/aws-terraform/storage-stack/variables.tf
Labels: enhancement

#95 feat: Switch gcp promote quarantine source to terraform archive
  post-scan-actions/gcp-python-promote-or-quarantine/Makefile
  post-scan-actions/gcp-python-promote-or-quarantine/README.md
  post-scan-actions/gcp-python-promote-or-quarantine/docs/deploy-tutorial.md
  post-scan-actions/gcp-python-promote-or-quarantine/main.tf
Labels: enhancement

#96 fix: Add Cloud One Regions and Endpoints
  post-scan-actions/aws-python-conformity-custom-check/handler.py
  post-scan-actions/aws-python-conformity-custom-check/template.yml
Labels: bug, enhancement

#88 feat(post-scan action): GCP Teams notification for FSS
  .gitignore
  post-scan-actions/gcp-python-teams-notification/.gitignore
  post-scan-actions/gcp-python-teams-notification/README.md
  post-scan-actions/gcp-python-teams-notification/docs/deploy-tutorial.md
  post-scan-actions/gcp-python-teams-notification/main.py
  post-scan-actions/gcp-python-teams-notification/package-lock.json
  post-scan-actions/gcp-python-teams-notification/package.json
  post-scan-actions/gcp-python-teams-notification/requirements.txt
  post-scan-actions/gcp-python-teams-notification/serverless.yml
Labels: new plugin

#98 docs: Remove squash steps from contributing guide
  .github/CONTRIBUTING.md
Labels: documentation
